"""Identity domain events - centralized event definitions.

This module provides a centralized location for all identity domain events,
organized by functional area for better maintainability.
"""

# Base events
from .base import IdentityDomainEvent

# User events
from .user_events import (
    UserCreated,
    UserActivated,
    UserSuspended,
    UserDeactivated,
    UserDeleted,
    UserReactivated,
    UserRegistered,
    UserReinstated,
    ProfileUpdated,
    ProfileCompleted,
    UserProfileUpdated,
    AvatarUploaded,
    AvatarChanged,
    AvatarDeleted,
    LoginSuccessful,
    LoginFailed,
    AccountLockedOut,
    AccountUnlocked,
    UserLocked,
    UserUnlocked,
    LoginAttemptRecorded,
    PasswordChanged,
    PasswordExpired,
    PasswordResetRequested,
    UserPasswordChanged,
    EmailVerificationRequested,
    EmailVerified,
    UserEmailChanged,
    PhoneNumberAdded,
    PhoneNumberVerified,
    PhoneNumberChanged,
    PhoneNumberRemoved,
    MFAEnabled,
    MFADisabled,
    UserMFAEnabled,
    UserMFADisabled,
    BackupCodeGenerated,
    BackupCodeUsed,
    BiometricRegistered,
    BiometricVerified,
    DeviceRegistered,
    DeviceTrusted,
    APIKeyCreated,
    APIKeyRevoked,
    EmergencyContactAdded,
    EmergencyContactVerified,
    RiskLevelChanged,
    UserExported,
    ConsentGranted,
    ConsentRevoked,
    UserSessionCreated,
    SessionRevoked,
    UserRoleAssigned,
    UserRoleRevoked,
    UserPermissionGranted,
    UserPermissionRevoked,
)

# Session events
from .session_events import (
    SessionCreated,
    SessionExpired,
    SessionTerminated,
    SessionSuspended,
    SessionResumed,
    TokenRefreshed,
    TokenRevoked,
    SessionMFACompleted,
    SessionPrivilegeElevated,
    SessionSecurityEvent,
    SessionLocationChanged,
    SessionRiskScoreChanged,
)

# Group events
from .group_events import (
    GroupCreated,
    GroupUpdated,
    GroupDeleted,
    GroupArchived,
    GroupRestored,
    GroupSuspended,
    GroupReactivated,
    MemberAdded,
    MemberRemoved,
    MemberRoleChanged,
    MembershipExpired,
    OwnershipTransferred,
    OwnerAdded,
    InvitationSent,
    InvitationAccepted,
    InvitationDeclined,
    InvitationRevoked,
    MembershipRequested,
    MembershipRequestApproved,
    MembershipRequestRejected,
    GroupSettingsUpdated,
    GroupVisibilityChanged,
    GroupJoinMethodChanged,
    SubgroupAdded,
    SubgroupRemoved,
    BulkMembersAdded,
    BulkMembersRemoved,
)

# Role events
from .role_events import (
    RoleCreated,
    RoleUpdated,
    RoleDeleted,
    RoleActivated,
    RoleDeactivated,
    RolePermissionGranted,
    RolePermissionRevoked,
    RoleHierarchyChanged,
    RoleAssigned,
    RoleUnassigned,
    RoleAssignmentExpired,
    RoleAssignmentSuspended,
    PermissionAddedToRole,
    PermissionRemovedFromRole,
)

# Permission events
from .permission_events import (
    PermissionCreated,
    PermissionUpdated,
    PermissionDeleted,
    PermissionActivated,
    PermissionDeactivated,
    PermissionHierarchyChanged,
    PermissionConstraintAdded,
    PermissionConstraintRemoved,
    PermissionCloned,
    PermissionMerged,
    PermissionGranted,
    PermissionRevoked,
)

# Security events
from .security_events import (
    SecurityAlertRaised,
    SuspiciousActivityDetected,
    IPAllowlisted,
    IPBlocklisted,
    AuditLogCreated,
    ComplianceViolationDetected,
)

# MFA events
from .mfa_events import (
    MFADeviceCreated,
    MFADeviceVerified,
    MFADeviceDisabled,
    MFACodeVerificationFailed,
)

# Token events
from .token_events import (
    TokenIssued,
    TokenFamilyRevoked,
)

__all__ = [
    # Base
    "IdentityDomainEvent",
    
    # User events
    "UserCreated",
    "UserActivated",
    "UserSuspended",
    "UserDeactivated",
    "UserDeleted",
    "UserReactivated",
    "UserRegistered",
    "UserReinstated",
    "ProfileUpdated",
    "ProfileCompleted",
    "UserProfileUpdated",
    "AvatarUploaded",
    "AvatarChanged",
    "AvatarDeleted",
    "LoginSuccessful",
    "LoginFailed",
    "AccountLockedOut",
    "AccountUnlocked",
    "UserLocked",
    "UserUnlocked",
    "LoginAttemptRecorded",
    "PasswordChanged",
    "PasswordExpired",
    "PasswordResetRequested",
    "UserPasswordChanged",
    "EmailVerificationRequested",
    "EmailVerified",
    "UserEmailChanged",
    "PhoneNumberAdded",
    "PhoneNumberVerified",
    "PhoneNumberChanged",
    "PhoneNumberRemoved",
    "MFAEnabled",
    "MFADisabled",
    "UserMFAEnabled",
    "UserMFADisabled",
    "BackupCodeGenerated",
    "BackupCodeUsed",
    "BiometricRegistered",
    "BiometricVerified",
    "DeviceRegistered",
    "DeviceTrusted",
    "APIKeyCreated",
    "APIKeyRevoked",
    "EmergencyContactAdded",
    "EmergencyContactVerified",
    "RiskLevelChanged",
    "UserExported",
    "ConsentGranted",
    "ConsentRevoked",
    "UserSessionCreated",
    "SessionRevoked",
    "UserRoleAssigned",
    "UserRoleRevoked",
    "UserPermissionGranted",
    "UserPermissionRevoked",
    
    # Session events
    "SessionCreated",
    "SessionExpired",
    "SessionTerminated",
    "SessionSuspended",
    "SessionResumed",
    "TokenRefreshed",
    "TokenRevoked",
    "SessionMFACompleted",
    "SessionPrivilegeElevated",
    "SessionSecurityEvent",
    "SessionLocationChanged",
    "SessionRiskScoreChanged",
    
    # Group events
    "GroupCreated",
    "GroupUpdated",
    "GroupDeleted",
    "GroupArchived",
    "GroupRestored",
    "GroupSuspended",
    "GroupReactivated",
    "MemberAdded",
    "MemberRemoved",
    "MemberRoleChanged",
    "MembershipExpired",
    "OwnershipTransferred",
    "OwnerAdded",
    "InvitationSent",
    "InvitationAccepted",
    "InvitationDeclined",
    "InvitationRevoked",
    "MembershipRequested",
    "MembershipRequestApproved",
    "MembershipRequestRejected",
    "GroupSettingsUpdated",
    "GroupVisibilityChanged",
    "GroupJoinMethodChanged",
    "SubgroupAdded",
    "SubgroupRemoved",
    "BulkMembersAdded",
    "BulkMembersRemoved",
    
    # Role events
    "RoleCreated",
    "RoleUpdated",
    "RoleDeleted",
    "RoleActivated",
    "RoleDeactivated",
    "RolePermissionGranted",
    "RolePermissionRevoked",
    "RoleHierarchyChanged",
    "RoleAssigned",
    "RoleUnassigned",
    "RoleAssignmentExpired",
    "RoleAssignmentSuspended",
    "PermissionAddedToRole",
    "PermissionRemovedFromRole",
    
    # Permission events
    "PermissionCreated",
    "PermissionUpdated",
    "PermissionDeleted",
    "PermissionActivated",
    "PermissionDeactivated",
    "PermissionHierarchyChanged",
    "PermissionConstraintAdded",
    "PermissionConstraintRemoved",
    "PermissionCloned",
    "PermissionMerged",
    "PermissionGranted",
    "PermissionRevoked",
    
    # Security events
    "SecurityAlertRaised",
    "SuspiciousActivityDetected",
    "IPAllowlisted",
    "IPBlocklisted",
    "AuditLogCreated",
    "ComplianceViolationDetected",
    
    # MFA events
    "MFADeviceCreated",
    "MFADeviceVerified",
    "MFADeviceDisabled",
    "MFACodeVerificationFailed",
    
    # Token events
    "TokenIssued",
    "TokenFamilyRevoked",
]