# EzzDay Backend - Infrastructure Monitoring Rules
# Prometheus alerting rules for infrastructure components

groups:
  - name: ezzday-infrastructure
    rules:
      # Container Health
      - alert: ContainerDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          service: ezzday-backend
        annotations:
          summary: "Container is down"
          description: "Container {{ $labels.instance }} has been down for more than 1 minute"

      - alert: ContainerRestarting
        expr: increase(container_restart_count[1h]) > 3
        for: 0s
        labels:
          severity: warning
          service: ezzday-backend
        annotations:
          summary: "Container restarting frequently"
          description: "Container {{ $labels.container }} has restarted {{ $value }} times in the last hour"

      # CPU Usage
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: ezzday-backend
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}%"

      - alert: VeryHighCPUUsage
        expr: rate(process_cpu_seconds_total[5m]) * 100 > 95
        for: 2m
        labels:
          severity: critical
          service: ezzday-backend
        annotations:
          summary: "Very high CPU usage"
          description: "CPU usage is {{ $value }}%"

      # Disk Space
      - alert: LowDiskSpace
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes > 0.8
        for: 5m
        labels:
          severity: warning
          service: ezzday-backend
        annotations:
          summary: "Low disk space"
          description: "Disk usage is {{ $value | humanizePercentage }} on {{ $labels.device }}"

      - alert: VeryLowDiskSpace
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes > 0.9
        for: 2m
        labels:
          severity: critical
          service: ezzday-backend
        annotations:
          summary: "Very low disk space"
          description: "Disk usage is {{ $value | humanizePercentage }} on {{ $labels.device }}"

      # Network Connectivity
      - alert: HighNetworkLatency
        expr: ping_rtt_seconds > 0.1
        for: 5m
        labels:
          severity: warning
          service: ezzday-backend
        annotations:
          summary: "High network latency"
          description: "Network latency is {{ $value }}s to {{ $labels.target }}"

  - name: ezzday-database
    rules:
      # PostgreSQL Monitoring
      - alert: PostgreSQLDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
          service: postgresql
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database is not responding"

      - alert: PostgreSQLTooManyConnections
        expr: pg_stat_database_numbackends / pg_settings_max_connections > 0.8
        for: 2m
        labels:
          severity: warning
          service: postgresql
        annotations:
          summary: "PostgreSQL too many connections"
          description: "PostgreSQL is using {{ $value | humanizePercentage }} of available connections"

      - alert: PostgreSQLSlowQueries
        expr: pg_stat_statements_mean_time_ms > 1000
        for: 5m
        labels:
          severity: warning
          service: postgresql
        annotations:
          summary: "PostgreSQL slow queries detected"
          description: "Average query time is {{ $value }}ms"

      - alert: PostgreSQLReplicationLag
        expr: pg_replication_lag_seconds > 30
        for: 2m
        labels:
          severity: warning
          service: postgresql
        annotations:
          summary: "PostgreSQL replication lag"
          description: "Replication lag is {{ $value }}s"

  - name: ezzday-redis
    rules:
      # Redis Monitoring
      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
          service: redis
        annotations:
          summary: "Redis is down"
          description: "Redis server is not responding"

      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.8
        for: 5m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "Redis high memory usage"
          description: "Redis memory usage is {{ $value | humanizePercentage }}"

      - alert: RedisHighConnections
        expr: redis_connected_clients > 100
        for: 5m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "Redis high connection count"
          description: "Redis has {{ $value }} connected clients"

      - alert: RedisSlowlog
        expr: increase(redis_slowlog_length[5m]) > 10
        for: 2m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "Redis slow queries detected"
          description: "{{ $value }} slow queries in the last 5 minutes"

  - name: ezzday-rabbitmq
    rules:
      # RabbitMQ Monitoring
      - alert: RabbitMQDown
        expr: rabbitmq_up == 0
        for: 1m
        labels:
          severity: critical
          service: rabbitmq
        annotations:
          summary: "RabbitMQ is down"
          description: "RabbitMQ server is not responding"

      - alert: RabbitMQHighQueueSize
        expr: rabbitmq_queue_messages > 1000
        for: 5m
        labels:
          severity: warning
          service: rabbitmq
        annotations:
          summary: "RabbitMQ high queue size"
          description: "Queue {{ $labels.queue }} has {{ $value }} messages"

      - alert: RabbitMQHighMemoryUsage
        expr: rabbitmq_node_mem_used / rabbitmq_node_mem_limit > 0.8
        for: 5m
        labels:
          severity: warning
          service: rabbitmq
        annotations:
          summary: "RabbitMQ high memory usage"
          description: "RabbitMQ memory usage is {{ $value | humanizePercentage }}"

      - alert: RabbitMQPartition
        expr: rabbitmq_node_partitions > 0
        for: 0s
        labels:
          severity: critical
          service: rabbitmq
        annotations:
          summary: "RabbitMQ network partition detected"
          description: "RabbitMQ cluster has {{ $value }} partitions"