# EzzDay Backend - Prometheus Configuration
# Metrics collection for production monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'production'
    service: 'ezzday-backend'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # Add alertmanager targets here when configured
          # - 'alertmanager:9093'

# Rule files for alerts
rule_files:
  - '/etc/prometheus/rules/*.yml'

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # FastAPI application metrics
  - job_name: 'ezzday-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: 
        - 'app:8000'
        labels:
          service: 'api'
          tier: 'backend'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+):.*'
        replacement: '${1}'

  # Nginx metrics (if nginx-prometheus-exporter is used)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          service: 'nginx'
          tier: 'frontend'

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: 
        - 'redis-exporter:9121'
        labels:
          service: 'redis'
          tier: 'cache'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+):.*'
        replacement: '${1}'

  # PostgreSQL metrics (if postgres-exporter is used)
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgresql'
          tier: 'database'

  # Celery metrics via Flower
  - job_name: 'celery'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['flower:5555']
        labels:
          service: 'celery'
          tier: 'workers'

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'system'

  # Cadvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'containers'
    metric_relabel_configs:
      # Drop unnecessary metrics to reduce cardinality
      - source_labels: [__name__]
        regex: 'container_(network_tcp_usage_total|network_udp_usage_total|tasks_state|cpu_load_average_10s)'
        action: drop

  # Blackbox exporter for endpoint monitoring
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - 'https://api.ezzday.com/health'
        - 'https://api.ezzday.com/docs'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

# Storage configuration
storage:
  tsdb:
    out_of_order_time_window: 30m

# Remote write configuration (optional)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint.com/write"
#     bearer_token: "your-token-here"
#     write_relabel_configs:
#       - source_labels: [__name__]
#         regex: 'prometheus_.*'
#         action: drop