"""
User Entity Module

User-related entities, events, errors, constants, and enums for user management.
"""

# Entities
from .emergency_contact import EmergencyContact
from .login_attempt import LoginAttempt
from .notification_setting import NotificationSetting
from .password_history import PasswordHistory
from .preference import UserPreference
from .profile import UserProfile

# Events
from .user_events import (
    APIKeyCreated,
    APIKeyRevoked,
    AccountLockedOut,
    AccountUnlocked,
    AvatarChanged,
    AvatarDeleted,
    AvatarUploaded,
    BackupCodeGenerated,
    BackupCodeUsed,
    BiometricRegistered,
    BiometricVerified,
    ConsentGranted,
    ConsentRevoked,
    DeviceRegistered,
    DeviceTrusted,
    EmailVerificationRequested,
    EmailVerified,
    EmergencyContactAdded,
    EmergencyContactVerified,
    LoginAttemptRecorded,
    LoginFailed,
    LoginSuccessful,
    MFADisabled,
    MFAEnabled,
    PasswordChanged,
    PasswordExpired,
    PasswordResetRequested,
    PhoneNumberAdded,
    PhoneNumberChanged,
    PhoneNumberRemoved,
    PhoneNumberVerified,
    ProfileCompleted,
    ProfileUpdated,
    RiskLevelChanged,
    SessionRevoked,
    UserActivated,
    UserCreated,
    UserDeactivated,
    UserDeleted,
    UserEmailChanged,
    UserExported,
    UserLocked,
    UserMFADisabled,
    UserMFAEnabled,
    UserPasswordChanged,
    UserPermissionGranted,
    UserPermissionRevoked,
    UserProfileUpdated,
    UserReactivated,
    UserRegistered,
    UserReinstated,
    UserRoleAssigned,
    UserRoleRevoked,
    UserSessionCreated,
    UserSuspended,
    UserUnlocked,
)

# Errors
from .user_errors import (
    AccountInactiveError,
    AccountLockedError,
    AccountSuspendedError,
    EmailNotVerifiedError,
    InvalidCredentialsError,
    InvalidMFACodeError,
    InvalidTokenError,
    MFARequiredError,
    PasswordExpiredError,
    PasswordPolicyViolationError,
    TokenExpiredError,
    TooManyLoginAttemptsError,
    UserAlreadyExistsError,
    UserNotFoundError,
    UsernameAlreadyExistsError,
    WeakPasswordError,
)
# Enums
from .user_enums import (
    AccountType,
    DateFormat,
    Department,
    Language,
    LoginFailureReason,
    NotificationChannel,
    Relationship,
    TimeFormat,
)

# Constants
from .user_constants import (
    AccountLockoutPolicy,
    ContactLimits,
    LoginLimits,
    NotificationLimits,
    PasswordHistoryPolicy,
    PasswordPolicy,
    PreferenceLimits,
    ProfileLimits,
    SecurityThresholds,
)

__all__ = [
    # === ENTITIES ===
    "EmergencyContact",
    "LoginAttempt",
    "NotificationSetting",
    "PasswordHistory",
    "UserPreference",
    "UserProfile",
    
    # === EVENTS ===
    "APIKeyCreated",
    "APIKeyRevoked",
    "AccountLockedOut",
    "AccountUnlocked",
    "AvatarChanged",
    "AvatarDeleted",
    "AvatarUploaded",
    "BackupCodeGenerated",
    "BackupCodeUsed",
    "BiometricRegistered",
    "BiometricVerified",
    "ConsentGranted",
    "ConsentRevoked",
    "DeviceRegistered",
    "DeviceTrusted",
    "EmailVerificationRequested",
    "EmailVerified",
    "EmergencyContactAdded",
    "EmergencyContactVerified",
    "LoginAttemptRecorded",
    "LoginFailed",
    "LoginSuccessful",
    "MFADisabled",
    "MFAEnabled",
    "PasswordChanged",
    "PasswordExpired",
    "PasswordResetRequested",
    "PhoneNumberAdded",
    "PhoneNumberChanged",
    "PhoneNumberRemoved",
    "PhoneNumberVerified",
    "ProfileCompleted",
    "ProfileUpdated",
    "RiskLevelChanged",
    "SessionRevoked",
    "UserActivated",
    "UserCreated",
    "UserDeactivated",
    "UserDeleted",
    "UserEmailChanged",
    "UserExported",
    "UserLocked",
    "UserMFADisabled",
    "UserMFAEnabled",
    "UserPasswordChanged",
    "UserPermissionGranted",
    "UserPermissionRevoked",
    "UserProfileUpdated",
    "UserReactivated",
    "UserRegistered",
    "UserReinstated",
    "UserRoleAssigned",
    "UserRoleRevoked",
    "UserSessionCreated",
    "UserSuspended",
    "UserUnlocked",
    
    # === ERRORS ===
    "AccountInactiveError",
    "AccountLockedError",
    "AccountSuspendedError",
    "EmailNotVerifiedError",
    "InvalidCredentialsError",
    "InvalidMFACodeError",
    "InvalidTokenError",
    "MFARequiredError",
    "PasswordExpiredError",
    "PasswordPolicyViolationError",
    "TokenExpiredError",
    "TooManyLoginAttemptsError",
    "UserAlreadyExistsError",
    "UserNotFoundError",
    "UsernameAlreadyExistsError",
    "WeakPasswordError",
    
    # === ENUMS ===
    "AccountType",
    "DateFormat",
    "Department",
    "Language",
    "LoginFailureReason",
    "NotificationChannel",
    "Relationship",
    "TimeFormat",
    
    # === CONSTANTS ===
    "AccountLockoutPolicy",
    "ContactLimits",
    "LoginLimits",
    "NotificationLimits",
    "PasswordHistoryPolicy",
    "PasswordPolicy",
    "PreferenceLimits",
    "ProfileLimits",
    "SecurityThresholds",
]

# Metadata
__version__ = "1.0.0"
__domain__ = "identity"