"""
Identity Domain Events - Compatibility Layer

This module provides backward compatibility for the old event imports.
All events have been moved to the centralized events package.
"""

# Import all events from the centralized location for backward compatibility
from .events import *

# Explicitly import the base class
from .events.base import IdentityDomainEvent

__all__ = [
    # Base
    "IdentityDomainEvent",
    
    # User events
    "UserCreated",
    "UserActivated",
    "UserSuspended",
    "UserDeactivated",
    "UserDeleted",
    "UserReactivated",
    "UserRegistered",
    "UserReinstated",
    "ProfileUpdated",
    "ProfileCompleted",
    "UserProfileUpdated",
    "AvatarUploaded",
    "AvatarChanged",
    "AvatarDeleted",
    "LoginSuccessful",
    "LoginFailed",
    "AccountLockedOut",
    "AccountUnlocked",
    "UserLocked",
    "UserUnlocked",
    "LoginAttemptRecorded",
    "PasswordChanged",
    "PasswordExpired",
    "PasswordResetRequested",
    "UserPasswordChanged",
    "EmailVerificationRequested",
    "EmailVerified",
    "UserEmailChanged",
    "PhoneNumberAdded",
    "PhoneNumberVerified",
    "PhoneNumberChanged",
    "PhoneNumberRemoved",
    "MFAEnabled",
    "MFADisabled",
    "UserMFAEnabled",
    "UserMFADisabled",
    "BackupCodeGenerated",
    "BackupCodeUsed",
    "BiometricRegistered",
    "BiometricVerified",
    "DeviceRegistered",
    "DeviceTrusted",
    "APIKeyCreated",
    "APIKeyRevoked",
    "EmergencyContactAdded",
    "EmergencyContactVerified",
    "RiskLevelChanged",
    "UserExported",
    "ConsentGranted",
    "ConsentRevoked",
    "UserSessionCreated",
    "SessionRevoked",
    "UserRoleAssigned",
    "UserRoleRevoked",
    "UserPermissionGranted",
    "UserPermissionRevoked",
    
    # Session events
    "SessionCreated",
    "SessionExpired",
    "SessionTerminated",
    "SessionSuspended",
    "SessionResumed",
    "TokenRefreshed",
    "TokenRevoked",
    "SessionMFACompleted",
    "SessionPrivilegeElevated",
    "SessionSecurityEvent",
    "SessionLocationChanged",
    "SessionRiskScoreChanged",
    
    # Group events
    "GroupCreated",
    "GroupUpdated",
    "GroupDeleted",
    "GroupArchived",
    "GroupRestored",
    "GroupSuspended",
    "GroupReactivated",
    "MemberAdded",
    "MemberRemoved",
    "MemberRoleChanged",
    "MembershipExpired",
    "OwnershipTransferred",
    "OwnerAdded",
    "InvitationSent",
    "InvitationAccepted",
    "InvitationDeclined",
    "InvitationRevoked",
    "MembershipRequested",
    "MembershipRequestApproved",
    "MembershipRequestRejected",
    "GroupSettingsUpdated",
    "GroupVisibilityChanged",
    "GroupJoinMethodChanged",
    "SubgroupAdded",
    "SubgroupRemoved",
    "BulkMembersAdded",
    "BulkMembersRemoved",
    
    # Role events
    "RoleCreated",
    "RoleUpdated",
    "RoleDeleted",
    "RoleActivated",
    "RoleDeactivated",
    "RolePermissionGranted",
    "RolePermissionRevoked",
    "RoleHierarchyChanged",
    "RoleAssigned",
    "RoleUnassigned",
    "RoleAssignmentExpired",
    "RoleAssignmentSuspended",
    "PermissionAddedToRole",
    "PermissionRemovedFromRole",
    
    # Permission events
    "PermissionCreated",
    "PermissionUpdated",
    "PermissionDeleted",
    "PermissionActivated",
    "PermissionDeactivated",
    "PermissionHierarchyChanged",
    "PermissionConstraintAdded",
    "PermissionConstraintRemoved",
    "PermissionCloned",
    "PermissionMerged",
    "PermissionGranted",
    "PermissionRevoked",
    
    # Security events
    "SecurityAlertRaised",
    "SuspiciousActivityDetected",
    "IPAllowlisted",
    "IPBlocklisted",
    "AuditLogCreated",
    "ComplianceViolationDetected",
    
    # MFA events
    "MFADeviceCreated",
    "MFADeviceVerified",
    "MFADeviceDisabled",
    "MFACodeVerificationFailed",
    "DeviceUntrusted",
    
    # Token events
    "TokenIssued",
    "TokenFamilyRevoked",
]