"""
GraphQL Schema Package for Identity Module

This package contains all GraphQL type definitions for the identity module,
including user types, authentication types, authorization types, and security types.
"""

# Auth types
from .auth_types import (
    ApiKeyCreateInput,
    ApiKeyFilterInput,
    ApiKeyType,
    ApiKeyUpdateInput,
    AuthenticationInput,
    DeviceInfoInput,
    DeviceInfoType,
    LoginAttemptFilterInput,
    LoginAttemptType,
    MFADeviceFilterInput,
    MFADeviceType,
    MFASetupInput,
    SessionConnection,
    SessionCreateInput,
    SessionEdge,
    SessionFilterInput,
    SessionType,
    SessionUpdateInput,
)

# Common types
from .common_types import (
    AddressInput,
    AddressType,
    AuditMetadataType,
    ConnectionType,
    ContactInfoInput,
    ContactInfoType,
    DateRangeInput,
    EdgeType,
    ErrorType,
    FilterInput,
    GeolocationInput,
    GeolocationResponse,
    MetadataType,
    OperationResultType,
    PageInfoType,
    PaginationInput,
    PaginationType,
    SortFieldInput,
    SortInput,
    SuccessType,
    ValidationErrorType,
)

# Enums
from .enums import (
    AccountTypeEnum,
    AuditActionEnum,
    AuthenticationMethodEnum,
    ComplianceStatusEnum,
    DateFormatEnum,
    DepartmentEnum,
    DeviceTypeEnum,
    InheritanceModeEnum,
    LanguageEnum,
    LoginFailureReasonEnum,
    MFAMethodEnum,
    NotificationChannelEnum,
    NotificationTypeEnum,
    PermissionEffectEnum,
    PermissionScopeEnum,
    PermissionTypeEnum,
    RelationshipEnum,
    ResourceTypeEnum,
    RiskLevelEnum,
    SecurityEventTypeEnum,
    SessionStatusEnum,
    SessionTypeEnum,
    SortDirection,
    TimeFormatEnum,
    UserRoleEnum,
    UserStatusEnum,
    VerificationStatusEnum,
)

# Role types
from .role_types import (
    PermissionCheckInput,
    PermissionCheckResult,
    PermissionConnection,
    PermissionCreateInput,
    PermissionEdge,
    PermissionFilterInput,
    PermissionType,
    PermissionUpdateInput,
    RoleAssignmentInput,
    RoleConnection,
    RoleCreateInput,
    RoleEdge,
    RoleFilterInput,
    RolePermissionType,
    RoleType,
    RoleUpdateInput,
    UserRoleType,
)

# Security types
from .security_types import (
    AuditLogFilterInput,
    AuditLogType,
    BlacklistCreateInput,
    BlacklistType,
    ComplianceReportType,
    NotificationCreateInput,
    NotificationFilterInput,
    NotificationType,
    SecurityEventCreateInput,
    SecurityEventFilterInput,
    SecurityEventType,
    SecurityEventUpdateInput,
)

# Schema components
from .schema import (
    IdentityMutations,
    IdentityQueries,
    IdentitySubscriptions,
    identity_schema,
)

# User types
from .user_types import (
    EmergencyContactInput,
    EmergencyContactType,
    UserConnection,
    UserCreateInput,
    UserEdge,
    UserFilterInput,
    UserListResponse,
    UserPreferencesInput,
    UserPreferencesType,
    UserProfileInput,
    UserProfileType,
    UserSortInput,
    UserSummaryType,
    UserType,
    UserUpdateInput,
)

__all__ = [
    "AccountTypeEnum",
    "AddressInput",
    "AddressType",
    "ApiKeyCreateInput",
    "ApiKeyFilterInput",
    "ApiKeyType",
    "ApiKeyUpdateInput",
    "AuditActionEnum",
    "AuditLogFilterInput",
    "AuditLogType",
    "AuditMetadataType",
    "AuthenticationInput",
    "AuthenticationMethodEnum",
    "BlacklistCreateInput",
    "BlacklistType",
    "ComplianceReportType",
    "ComplianceStatusEnum",
    "ConnectionType",
    "ContactInfoInput",
    "ContactInfoType",
    "DateFormatEnum",
    "DateRangeInput",
    "DepartmentEnum",
    "DeviceInfoInput",
    # Auth types
    "DeviceInfoType",
    "DeviceTypeEnum",
    "EdgeType",
    "EmergencyContactInput",
    # User types
    "EmergencyContactType",
    "ErrorType",
    "FilterInput",
    "GeolocationInput",
    "GeolocationResponse",
    "InheritanceModeEnum",
    "LanguageEnum",
    "LoginAttemptFilterInput",
    "LoginAttemptType",
    "LoginFailureReasonEnum",
    "MFADeviceFilterInput",
    "MFADeviceType",
    "MFAMethodEnum",
    "MFASetupInput",
    "MetadataType",
    "NotificationChannelEnum",
    "NotificationCreateInput",
    "NotificationFilterInput",
    "NotificationType",
    "NotificationTypeEnum",
    "OperationResultType",
    "PageInfoType",
    "PaginationInput",
    # Common types
    "PaginationType",
    "PermissionCheckInput",
    "PermissionCheckResult",
    "PermissionConnection",
    "PermissionCreateInput",
    "PermissionEdge",
    "PermissionEffectEnum",
    "PermissionFilterInput",
    "PermissionScopeEnum",
    # Role types
    "PermissionType",
    "PermissionTypeEnum",
    "PermissionUpdateInput",
    "RelationshipEnum",
    "ResourceTypeEnum",
    "RiskLevelEnum",
    "RoleAssignmentInput",
    "RoleConnection",
    "RoleCreateInput",
    "RoleEdge",
    "RoleFilterInput",
    "RolePermissionType",
    "RoleType",
    "RoleUpdateInput",
    "SecurityEventCreateInput",
    "SecurityEventFilterInput",
    # Security types
    "SecurityEventType",
    "SecurityEventTypeEnum",
    "SecurityEventUpdateInput",
    "SessionConnection",
    "SessionCreateInput",
    "SessionEdge",
    "SessionFilterInput",
    "SessionStatusEnum",
    "SessionType",
    "SessionTypeEnum",
    "SessionUpdateInput",
    "SortDirection",
    "SortFieldInput",
    "SortInput",
    "SuccessType",
    "TimeFormatEnum",
    "UserConnection",
    "UserCreateInput",
    "UserEdge",
    "UserFilterInput",
    "UserListResponse",
    "UserPreferencesInput",
    "UserPreferencesType",
    "UserProfileInput",
    "UserProfileType",
    "UserRoleEnum",
    "UserRoleType",
    "UserSortInput",
    # Enums
    "UserStatusEnum",
    "UserSummaryType",
    "UserType",
    "UserUpdateInput",
    "ValidationErrorType",
    "VerificationStatusEnum",
    # Schema components
    "IdentityMutations",
    "IdentityQueries",
    "IdentitySubscriptions",
    "identity_schema",
]